services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: app
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "$PORT:80"
    restart: always
