name: Build and publish docker image

on:
  push:
    branches:
      - main
      - feat/docker-publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convert repository name to lowercase
        id: lowercase-repo
        run: |
          LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "lowercase_repo=$LOWERCASE_REPO" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.lowercase_repo }}/cloud-computing-app:latest --file Dockerfile .

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.lowercase_repo }}/cloud-computing-app:latest
